"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var user_1 = require("./model/user");
var articles_1 = require("./model/articles");
var animal_1 = require("./modules/animal");
var user = new user_1.UserBean();
user.username = 'fqj';
user.password = '123456';
user_1.UserModel.add(user);
var userInfo = user_1.UserModel.get(123);
console.log(userInfo);
var article = new articles_1.ArticleBean();
article.title = 'news';
article.desc = 'the best news';
articles_1.ArticleModel.add(article);
var aDog = new animal_1.A.Dog('jia fei mao');
var bDog = new animal_1.B.Dog('jia fei mao');
aDog.eat();
bDog.eat();
